#!/bin/bash
# caddy-regen.sh — Regenerate Caddyfile from running worktree pods.
#
# Scans all running worktree-* pods, reads their published port mappings,
# generates reverse proxy routes for each one, writes infra/local/Caddyfile,
# and reloads Caddy.
#
# Networking: Caddy runs with --network=host and routes to localhost:<port>.
# Each pod publishes deterministic ports derived from its hash.
#
# Usage: ./infra/local/caddy-regen.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CADDYFILE="$SCRIPT_DIR/Caddyfile"
CADDY_CONTAINER="frontman-caddy"

# Collect running worktree pods
PODS=$(podman pod ls --format '{{.Name}}' --filter status=running 2>/dev/null | grep '^worktree-' || true)

# Start generating Caddyfile
cat > "$CADDYFILE" << 'HEADER'
# Auto-generated by caddy-regen.sh — DO NOT EDIT MANUALLY
# Regenerate with: ./infra/local/caddy-regen.sh

HEADER

if [ -z "$PODS" ]; then
    # No pods running — write a minimal Caddyfile so Caddy doesn't error
    cat >> "$CADDYFILE" << 'EOF'
# No worktree pods currently running.
# Create one with: make wt-new BRANCH=feature/my-feature
:9999 {
    respond "No worktree pods running" 503
}
EOF
else
    for POD in $PODS; do
        # Extract hash from pod name (worktree-HASH)
        HASH="${POD#worktree-}"

        # Derive ports from hash (must match wt-pod-create)
        BASE_PORT=$(( 16#${HASH} % 5000 + 10000 ))
        PORT_PHOENIX=$((BASE_PORT))
        PORT_VITE=$((BASE_PORT + 1))
        PORT_NEXTJS=$((BASE_PORT + 2))
        PORT_STORYBOOK=$((BASE_PORT + 3))
        PORT_MARKETING=$((BASE_PORT + 4))
        PORT_DOGFOOD=$((BASE_PORT + 5))

        # Generate route blocks for this worktree
        cat >> "$CADDYFILE" << EOF
# Worktree: $POD (ports ${PORT_PHOENIX}–${PORT_DOGFOOD})
${HASH}.api.frontman.local {
    tls internal
    reverse_proxy https://localhost:${PORT_PHOENIX} {
        transport http {
            tls_insecure_skip_verify
        }
    }
}

${HASH}.vite.frontman.local {
    tls internal
    reverse_proxy localhost:${PORT_VITE}
}

${HASH}.nextjs.frontman.local {
    tls internal
    reverse_proxy localhost:${PORT_NEXTJS}
}

${HASH}.storybook.frontman.local {
    tls internal
    reverse_proxy localhost:${PORT_STORYBOOK}
}

${HASH}.dogfood.frontman.local {
    tls internal
    reverse_proxy localhost:${PORT_DOGFOOD}
}

${HASH}.marketing.frontman.local {
    tls internal
    reverse_proxy localhost:${PORT_MARKETING}
}

EOF
    done
fi

echo "Generated $CADDYFILE"

# Reload Caddy if running
if podman container inspect "$CADDY_CONTAINER" &>/dev/null; then
    podman exec "$CADDY_CONTAINER" caddy reload --config /etc/caddy/Caddyfile 2>/dev/null && \
        echo "Caddy reloaded" || \
        echo "Warning: Caddy reload failed (container may not be running)"
else
    echo "Note: Caddy container ($CADDY_CONTAINER) not running — skipping reload"
fi
